game:
  instructionTimeLimit: ${INSTRUCTION_TIME_LIMIT:5}
  minScoreToTerminate: ${MIN_SCORE_TO_TERMINATE:-3}
  maxScoreToTerminate: ${MAX_SCORE_TO_TERMINATE:10}
  maxContinuousAttempt: ${MAX_CONTINUOUS_ATTEMPT:10}